# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/roboy_plexus/roboy_plexus.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus || ORIG_REF_NAME==roboy_plexus} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_processing_system7_0_0/roboy_plexus_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_processing_system7_0_0 || ORIG_REF_NAME==roboy_plexus_processing_system7_0_0} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_myoControl_0_3/roboy_plexus_myoControl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_myoControl_0_3 || ORIG_REF_NAME==roboy_plexus_myoControl_0_3} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_ps7_0_axi_periph_0/roboy_plexus_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_ps7_0_axi_periph_0 || ORIG_REF_NAME==roboy_plexus_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_rst_ps7_0_49M_0 || ORIG_REF_NAME==roboy_plexus_rst_ps7_0_49M_0} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_xbar_0/roboy_plexus_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_xbar_0 || ORIG_REF_NAME==roboy_plexus_xbar_0} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_myoControl_0_4/roboy_plexus_myoControl_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_myoControl_0_4 || ORIG_REF_NAME==roboy_plexus_myoControl_0_4} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_myoControl_1_0/roboy_plexus_myoControl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_myoControl_1_0 || ORIG_REF_NAME==roboy_plexus_myoControl_1_0} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_myoControl_2_0/roboy_plexus_myoControl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_myoControl_2_0 || ORIG_REF_NAME==roboy_plexus_myoControl_2_0} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_myoControl_3_0/roboy_plexus_myoControl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_myoControl_3_0 || ORIG_REF_NAME==roboy_plexus_myoControl_3_0} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_tri_state_buffer_0_1/roboy_plexus_tri_state_buffer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_tri_state_buffer_0_1 || ORIG_REF_NAME==roboy_plexus_tri_state_buffer_0_1} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/roboy_plexus_gmii_to_rgmii_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_gmii_to_rgmii_0_1 || ORIG_REF_NAME==roboy_plexus_gmii_to_rgmii_0_1} -quiet] -quiet

# IP: bd/roboy_plexus/ip/roboy_plexus_auto_pc_0/roboy_plexus_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==roboy_plexus_auto_pc_0 || ORIG_REF_NAME==roboy_plexus_auto_pc_0} -quiet] -quiet

# XDC: bd/roboy_plexus/roboy_plexus_ooc.xdc
