# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0.xci
# IP: The module: 'roboy_plexus_rst_ps7_0_49M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0.xci
# IP: The module: 'roboy_plexus_rst_ps7_0_49M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_rst_ps7_0_49M_0/roboy_plexus_rst_ps7_0_49M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
