# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/roboy_plexus_gmii_to_rgmii_0_1.xci
# IP: The module: 'roboy_plexus_gmii_to_rgmii_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/synth/roboy_plexus_gmii_to_rgmii_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_gmii_to_rgmii_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/synth/roboy_plexus_gmii_to_rgmii_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_gmii_to_rgmii_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/synth/roboy_plexus_gmii_to_rgmii_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_gmii_to_rgmii_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/roboy_plexus_gmii_to_rgmii_0_1.xci
# IP: The module: 'roboy_plexus_gmii_to_rgmii_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/synth/roboy_plexus_gmii_to_rgmii_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_gmii_to_rgmii_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/synth/roboy_plexus_gmii_to_rgmii_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_gmii_to_rgmii_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/letrend/workspace/snickerdoodle/snickerdoodle.srcs/sources_1/bd/roboy_plexus/ip/roboy_plexus_gmii_to_rgmii_0_1/synth/roboy_plexus_gmii_to_rgmii_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'roboy_plexus_gmii_to_rgmii_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
